### ISSUE TITLE
Unable to pull Version 1.1.1 from pod update

### ISSUE THREAD

**Issue by alizaheer** [d2soft/NimbbLibrary-iOS#1]
Hi

NimbbLibrary.podspec is updated to 1.1.0 but tag not created for it , so unable to pull latest code. Can you let me know how to pull latest code via pod

**Comment by olilavoie** [comment]
Tag 1.1.0 was pushed moment ago. It should work now.

**Comment by alizaheer** [comment]
@FouZ  Still not able to update 

pod ~> "pod 'NimbbLibrary', '~> 1.1.0'"
Error ~> http://screencast.com/t/VnG0MEbKt

**Comment by olilavoie** [comment]
The issue is now on the cocoapods side. they changed the update process. currently waiting for approbation on their side tu push the updated version there. will keep you updated when its done.

**Comment by alizaheer** [comment]
@FouZ its been two days ,pod update specs in just 15 mins more or less. you send updated specs to cocoapods/specs?
ForInfo : https://guides.cocoapods.org/making/specs-and-specs-repo.html#how-do-i-update-an-existing-pod

**Comment by olilavoie** [comment]
Problem was with the ownership process of the pod since the initial release didn't use their new trunk process. Now, the issue is fixed. Regards.
